name: ClearML Checks
on:
  branches:
    - feature/*

jobs:
  import-pbp-data:
    runs-on: self-hosted
    steps:
      - name: Code is Remotely Runnable
        uses: allegroai/clearml-actions-check-remotely-runnable@main
        with:
          QUEUE_NAME: 'default'
          EXECUTION_ENTRYPOINT: 'src/import_pbp_data.py'
          CLEARML_API_ACCESS_KEY: ${{ secrets.CLEARML_API_ACCESS_KEY }}
          CLEARML_API_SECRET_KEY: ${{ secrets.CLEARML_API_SECRET_KEY }}
          CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}
