name: Update PBP Dataset

on:
  push:
    branches:
      - main

env:
    CLEARML_API_ACCESS_KEY: ${{ secrets.CLEARML_API_ACCESS_KEY }}
    CLEARML_API_SECRET_KEY: ${{ secrets.CLEARML_API_SECRET_KEY }}
    CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}

jobs:
  update-pbp-dataset:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: python -m pip install .

      - name: Run Import PBP Data
        run: python -m import_pbp_data